### ISSUE TITLE
Import ecies keys from ecdsa keys

### ISSUE THREAD

**Issue by udhos** [ecies/go#16]
Hi,

How can I import ecies keys from existing ecdsa keys?

* ecies.PrivateKey from ecdsa.PrivateKey
* ecies.PublicKey from ecdsa.PublicKey

ecdsa: https://golang.org/pkg/crypto/ecdsa/
ecies: https://github.com/ecies/go

Thanks,
Everton

**Comment by kigawas** [comment]
You have to use the same elliptic curve, which is secp256k1, and import it with hex string or bytes

**Comment by udhos** [comment]
I see that there helper functions to import ecies keys from bytes. But how to properly export ecdsa keys to bytes?

**Comment by kigawas** [comment]
You can check the documentation of ecdsa.

It's just a big int, you can convert it to bytes.

**Comment by L11R** [comment]
Well, sure I can add the helper function that accepts `ecdsa.PrivateKey`; the problem is that this private key MUST BE `secp256k1` curve.

I hope library user SHOULD understand how it works and be able to write such a function himself.

**Comment by udhos** [comment]
In my specific case, the ecdsa key is P256:

> P256 returns a Curve which implements NIST P-256 (FIPS 186-3, section D.2.3), also known as secp256r1 or prime256v1. The CurveParams.Name of this Curve is "P-256".

Can I just export its big Int D data as []byte and feed It into NewPrivateKeyFromBytes() ?

**Comment by L11R** [comment]
@udhos well, currently this library set does NOT support `secp256r1` or anything else except `secp256k1`.

We already discuss it here: https://github.com/ecies/py/issues/81
