### ISSUE TITLE
Is there a java version?

### ISSUE THREAD

**Issue by bitcard** [ecies/go#21]

**Comment by kigawas** [comment]
You can try using JNI to call the [pure Rust implementation](https://github.com/ecies/rs#optional-pure-rust-aes-backend).

**Comment by bitcard** [comment]
> pure Rust implementation

Thank you reply so quickly, I need a java version, is compatible with https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/crypto/ECIESCoder.java?

**Comment by kigawas** [comment]
Probably not. 
There is no international standard for ECIES, so the implementation varies.

**Comment by bitcard** [comment]
> Probably not. There is no international standard for ECIES, so the implementation varies.

thank you
