### ISSUE TITLE
How to load a certificate file

### ISSUE THREAD

**Issue by liulanghan8023** [ecies/go#33]
Hello! Can you give  a demo that loads keys from a file? Thank you very much!

**Comment by kigawas** [comment]
It has to be a byte array of secp256k1 key. 

I don't know what your certificate is, maybe you can check https://www.ssl.com/how-to/export-certificates-private-key-from-pkcs12-file-with-openssl/ to export the private key as a PEM format.

If you get something like (note the "EC"):
```
-----BEGIN EC PRIVATE KEY-----
BASE64 ENCODED DATA
-----END EC PRIVATE KEY-----
```

Then you can try decoding this PEM format with [coincurve](https://ofek.dev/coincurve/api/#coincurve.keys.PrivateKey.from_pem)
