### ISSUE TITLE
checksum mismatch when go get 

### ISSUE THREAD

**Issue by junlicn** [ecies/go#34]
go get github.com/ecies/go/v2
go: downloading github.com/ecies/go/v2 v2.0.3
go: github.com/ecies/go/v2@v2.0.3: verifying module: checksum mismatch
        downloaded: h1:gosZ7+G8LFo0NHPGR7//Lcj7r5gzVRthWl/De3QVay8=
        sum.golang.org: h1:rtz3x6uw+if+lt4a39JnCi7M/B35l1JShCXTOBe3LPw=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by L11R** [comment]
@junlicn cannot reproduce. But I've prepared small v2.0.4 release with dependency updates.

**Comment by L11R** [comment]
Reopen if you still have this problem.
