### ISSUE TITLE
How to load key generate by openssl?

### ISSUE THREAD

**Issue by zhanglc** [ecies/go#84]
Hello, I'm using `github.com/ecies/go/v2 v2.0.7`,  try to load a public key by openssl , and got the follow error:

```goalng
panic: cannot parse public key                       
                                                     
goroutine 1 [running]:                               
main.main()               
```

the ecc public key is generate by the follow:

```shell
openssl version
OpenSSL 1.1.1n  15 Mar 2022

 openssl ecparam -genkey -name secp256k1 -out ecc_private_key.pem
 openssl ec -in ecc_private_key.pem -pubout -out ecc_public_key.pem
```

test go file:

```goalng
package main

import (
	"encoding/pem"
	ecies "github.com/ecies/go/v2"
	"log"
)

func main() {
	pubStr := `
-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvO6PRdLyD0EaRkFkfCeptcpey/P3ziHS
cbLbD96xg22JOvC3YYVtzyp4nVEyz+a07tonu3/pfEMstSiil1mEiw==
-----END PUBLIC KEY-----
	`
	block, _ := pem.Decode([]byte(pubStr))

	pub, err := ecies.NewPublicKeyFromBytes(block.Bytes)
	if err != nil {
		panic(err)
	}
	log.Println(pub)

}
```

**Comment by kigawas** [comment]
You need to convert the pem format to bytes

**Comment by kigawas** [comment]
By the way, the public key above is `04418834F5012C808A1183056301006072A8648CE3D020106052B8104000A03420004BCEE8F45D2F20F411A4641647C27A9B5CA5ECBF3F7CE21D271B2DB0FDEB1836D893AF0B761856DCF2A789D5132CFE6B4EEDA27BB7FE97C432CB528A29759848B010D0CF5012C808A118`

**Comment by zhanglc** [comment]
thanks a lot , the public key is ASN.1 format, we should convert and extract public key data area  from it .
